### ISSUE TITLE
Deactivation of "Include current article" does not work

### ISSUE THREAD

**Issue by heimseiten** [fritzmg/contao-news-related#1]
I installed a fresh Contao 5.3.7 with the [Contao Demo](https://github.com/contao/contao-demo).

When "Include current article" is not checked, the current article is viewed in the frontend.

<img width="897" alt="Bildschirmfoto 2024-04-23 um 18 10 32" src="https://github.com/fritzmg/contao-news-related/assets/6552484/4de959fc-db40-4d4a-9800-9763328fd58a">

**Comment by fritzmg** [comment]
So you

1. Edited a news article.
2. Selected one ore more news articles as related news articles for that news article.
3. You created the "News - Latest - Related" newslist module and integrated that into the news reader page.
4. You opened the news detail page of the news article of 1.) and it shows that same news article as well in the related news list on the reader page?

**Comment by heimseiten** [comment]
I checked it again. Yes.

**Comment by fritzmg** [comment]
As discussed on Slack everything is working as intended.
